logger:
  project: 'your_project_name'

trainer:
  max_epochs: 1000
  precision: '16-mixed'

generator:
  in_channels: 1
  initial_channel: 64
  num_rrdb_blocks: 16
  upscale_factor: 4
  lr: 0.0001

data:
  train_path: "data/train.pt"
  val_path: "data/val.pt"
  test_path: "data/test.pt"
  batch_size: 32
  num_workers: 12

callbacks:
  checkpoint:
    dirpath: "checkpoints/"
    filename: "rrdb-{epoch:02d}-{val_loss:.2f}"
    save_top_k: 3
    monitor: "val_loss"
    mode: "min"
    save_last: True
