model:
  vae_path: "drive/MyDrive/vae-epoch=19.ckpt"  # Path to pretrained VAE checkpoint
  
  unet:
    image_channels: 4  # 3 (latent) + 1 (condition)
    n_channels: 64    # Base channel multiplier
    channels_factors: [1, 2, 3, 4]  # Channel multipliers at each resolution
    att: [false, false, False, False]  # Attention at each resolution
    n_blocks: 2       # Number of residual blocks per resolution
    lr: 0.0001       # Learning rate for UNet
