# Model configurations
 model:
    generator:
      in_channels: 1
      num_rrdb_blocks: 4
      lr: 0.0001

    discriminator:
      in_channels: 1
      channel_list: [16, 32, 64, 128]
      lr: 0.000001

    label_smoothing:
      real_val: 0.9
      fake_val: 0.1

    loss:
      alpha: 0.001
      beta: 1.0
      gamma: 0.01
        # gamma
