logger:
  project: 'your_project_name'

trainer:
  max_epochs: 1000
  precision: '16-mixed'


data:
  train_path: "data/train.pt"
  val_path: "data/val.pt"
  test_path: "data/test.pt"
  batch_size: 32
  num_workers: 12

callbacks:
  checkpoint:
    dirpath: "drive/MyDrive/"
    filename: "gan-{epoch:02d}"
    every_n_epochs: 10
    save_top_k: -1  # Keep all checkpoints
    save_on_train_epoch_end: True

  image_logger:
    log_freq: 100  # Log images every 100 batches
