logger:
  project: 'your_project_name'

trainer:
  max_epochs: 1000
  precision: '16-mixed'


data:
  train_path: "data/train.pt"
  val_path: "data/val.pt"
  test_path: "data/test.pt"
  batch_size: 32
  num_workers: 12

callbacks:
  checkpoint:
    dirpath: "checkpoints/"
    filename: "rrdb-{epoch:02d}-{val_loss:.2f}"
    save_top_k: 3
    monitor: "val_loss"
    mode: "min"
    save_last: True
  
  image_logger:
    log_freq: 100  # Log images every 100 batches
